import jsPDF from 'jspdf';
import { GeneratedProtocol, Recommendation } from '@/lib/consultation/types';

const C = {
  sage:     [107, 142, 127] as const,
  sageDark: [74, 105, 92] as const,
  sageTint: [237, 243, 240] as const,
  gold:     [201, 166, 107] as const,
  goldDark: [150, 112, 55] as const,
  goldTint: [245, 238, 224] as const,
  cream:    [250, 250, 248] as const,
  card:     [255, 255, 255] as const,
  char:     [44, 44, 44] as const,
  body:     [66, 66, 66] as const,
  muted:    [100, 100, 100] as const,
  border:   [229, 226, 219] as const,
  safeBg:   [251, 246, 236] as const,
  safeInk:  [138, 109, 59] as const,
  white:    [255, 255, 255] as const,
};

type RGB = readonly [number, number, number];

const PAGE_W = 612;
const PAGE_H = 792;
const M = 54;
const CW = PAGE_W - M * 2;
const FOOTER_LINE = 754;
const FOOTER_TXT = 770;
const CONTENT_BOTTOM = 730;

function fill(d: jsPDF, c: RGB) { d.setFillColor(c[0], c[1], c[2]); }
function stroke(d: jsPDF, c: RGB) { d.setDrawColor(c[0], c[1], c[2]); }
function ink(d: jsPDF, c: RGB) { d.setTextColor(c[0], c[1], c[2]); }

function mapType(type: string): string {
  if (type === 'herb') return 'Herb';
  if (type === 'essential_oil') return 'Essential Oil';
  return 'Supplement';
}

function isHerbType(type: string): boolean {
  return type === 'herb' || type === 'essential_oil';
}

function card(d: jsPDF, x: number, y: number, w: number, rec: Recommendation, num: number, draw: boolean): number {
  const padX = 16, padTop = 12, padBottom = 12;
  const ix = x + padX;
  const iw = w - padX * 2;
  let cy = y + padTop;

  const badge = 20;
  const nameX = ix + badge + 12;
  const displayType = mapType(rec.type);
  const herbLike = isHerbType(rec.type);

  d.setFont('helvetica', 'bold'); d.setFontSize(7.5);
  const tagTxt = displayType.toUpperCase();
  const tagW = d.getTextWidth(tagTxt) + 14;
  const tagH = 15;
  const tagBg = herbLike ? C.sageTint : C.goldTint;
  const tagFg = herbLike ? C.sageDark : C.goldDark;

  if (draw) {
    fill(d, C.sage); d.roundedRect(ix, cy, badge, badge, 5, 5, 'F');
    ink(d, C.white); d.setFont('helvetica', 'bold'); d.setFontSize(11);
    d.text(String(num), ix + badge / 2, cy + badge / 2 + 3.8, { align: 'center' });

    ink(d, C.char); d.setFont('helvetica', 'bold'); d.setFontSize(13.5);
    d.text(rec.name, nameX, cy + 14.5);

    const tagX = x + w - padX - tagW;
    fill(d, tagBg); d.roundedRect(tagX, cy + 2.5, tagW, tagH, 7, 7, 'F');
    ink(d, tagFg); d.setFont('helvetica', 'bold'); d.setFontSize(7.5);
    d.text(tagTxt, tagX + tagW / 2, cy + 2.5 + tagH / 2 + 2.5, { align: 'center' });
  }
  cy += badge + 10;

  const col2 = ix + iw * 0.5;
  if (draw) {
    d.setFont('helvetica', 'bold'); d.setFontSize(7.5); ink(d, C.goldDark);
    d.text('DOSAGE', ix, cy); d.text('TIMING', col2, cy);
  }
  cy += 12;
  if (draw) {
    d.setFont('helvetica', 'bold'); d.setFontSize(10.5); ink(d, C.char);
    d.text(rec.dosage, ix, cy);
    d.text(rec.timing, col2, cy);
  }
  cy += 16;

  if (draw) { d.setFont('helvetica', 'bold'); d.setFontSize(7); ink(d, C.muted); d.text('WHY THIS', ix, cy); }
  cy += 10;
  d.setFont('helvetica', 'normal'); d.setFontSize(9.5);
  const lines = d.splitTextToSize(rec.rationale, iw);
  if (draw) { ink(d, C.body); d.text(lines, ix, cy, { lineHeightFactor: 1.24 }); }
  cy += lines.length * 11.5;

  if (rec.cautions) {
    cy += 7;
    d.setFont('helvetica', 'italic'); d.setFontSize(8);
    const sLines = d.splitTextToSize('Safety   ' + rec.cautions, iw - 22);
    const bandH = sLines.length * 9.5 + 11;
    if (draw) {
      fill(d, C.safeBg); d.roundedRect(ix, cy, iw, bandH, 5, 5, 'F');
      fill(d, C.gold); d.roundedRect(ix, cy, 3, bandH, 1.5, 1.5, 'F');
      ink(d, C.safeInk); d.setFont('helvetica', 'italic'); d.setFontSize(8);
      d.text(sLines, ix + 13, cy + 11, { lineHeightFactor: 1.3 });
    }
    cy += bandH;
  }

  cy += padBottom;
  return cy - y;
}

function disclaimer(d: jsPDF, x: number, y: number, w: number, text: string, draw: boolean): number {
  const pad = 12;
  const iw = w - pad * 2;
  d.setFont('helvetica', 'normal'); d.setFontSize(7.5);
  const lines = d.splitTextToSize(text, iw);
  const h = 11 + 10 + lines.length * 9.5 + 11;
  if (draw) {
    fill(d, C.cream); stroke(d, C.border); d.setLineWidth(0.75);
    d.roundedRect(x, y, w, h, 8, 8, 'FD');
    d.setFont('helvetica', 'bold'); d.setFontSize(7.5); ink(d, C.muted);
    d.text('DISCLAIMER', x + pad, y + 13);
    d.setFont('helvetica', 'normal'); d.setFontSize(7.5); ink(d, C.muted);
    d.text(lines, x + pad, y + 24, { lineHeightFactor: 1.26 });
  }
  return h;
}

function drawFooter(d: jsPDF, pageNum: number, pageCount: number) {
  stroke(d, C.border); d.setLineWidth(0.75);
  d.line(M, FOOTER_LINE, PAGE_W - M, FOOTER_LINE);
  d.setFont('helvetica', 'normal'); d.setFontSize(8); ink(d, C.muted);
  d.text('Generated by NatureScripts', M, FOOTER_TXT);
  d.text('naturescripts.io', PAGE_W - M, FOOTER_TXT, { align: 'right' });
  if (pageCount > 1) {
    d.text('Page ' + pageNum + ' of ' + pageCount, PAGE_W / 2, FOOTER_TXT, { align: 'center' });
  }
}

function pageBg(d: jsPDF) { fill(d, C.cream); d.rect(0, 0, PAGE_W, PAGE_H, 'F'); }

export async function generateProtocolPdf(
  protocol: GeneratedProtocol,
  userName?: string
): Promise<Blob> {
  const d = new jsPDF({ unit: 'pt', format: 'letter', compress: true });
  pageBg(d);

  // Header
  d.setFont('helvetica', 'bold'); d.setFontSize(20); ink(d, C.char);
  d.text('Nature', M, 66);
  const nW = d.getTextWidth('Nature');
  d.setFont('helvetica', 'normal'); ink(d, C.sage);
  d.text('Scripts', M + nW, 66);

  d.setFont('helvetica', 'bold'); d.setFontSize(8.5); ink(d, C.gold);
  d.text('P E R S O N A L I Z E D   W E L L N E S S   P R O T O C O L', PAGE_W - M, 62, { align: 'right' });

  stroke(d, C.sage); d.setLineWidth(1.4); d.line(M, 80, PAGE_W - M, 80);

  // Meta bar
  const mbY = 90, mbH = 28;
  fill(d, C.sageTint); d.roundedRect(M, mbY, CW, mbH, 6, 6, 'F');
  const mbBase = mbY + mbH / 2 + 3.3;

  const dateStr = new Date(protocol.created_at || Date.now()).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });

  if (userName) {
    d.setFont('helvetica', 'normal'); d.setFontSize(9); ink(d, C.muted);
    d.text('Prepared for', M + 16, mbBase);
    const pfW = d.getTextWidth('Prepared for');
    d.setFont('helvetica', 'bold'); ink(d, C.char);
    d.text(userName, M + 16 + pfW + 8, mbBase);
  }

  d.setFont('helvetica', 'bold'); d.setFontSize(9); ink(d, C.char);
  d.text(dateStr, PAGE_W - M - 16, mbBase, { align: 'right' });
  const dvW = d.getTextWidth(dateStr);
  d.setFont('helvetica', 'normal'); ink(d, C.muted);
  d.text('Date', PAGE_W - M - 16 - dvW - 8, mbBase, { align: 'right' });

  // Protocol title + summary
  d.setFont('helvetica', 'bold'); d.setFontSize(8.5); ink(d, C.sage);
  d.text('Y O U R   P R O T O C O L', M, 140);

  const title = protocol.title || 'Your Wellness Protocol';
  d.setFont('helvetica', 'bold'); d.setFontSize(22); ink(d, C.char);
  d.text(title, M, 165);

  let y = 184;
  d.setFont('helvetica', 'normal'); d.setFontSize(10.5); ink(d, C.body);
  const sumLines = d.splitTextToSize(protocol.summary, CW);
  d.text(sumLines, M, y, { lineHeightFactor: 1.32 });
  y += sumLines.length * 13.8 + 10;

  // Recommendations section header
  const recs = protocol.recommendations || [];
  d.setFont('helvetica', 'bold'); d.setFontSize(9); ink(d, C.char);
  const secLabel = 'RECOMMENDATIONS';
  d.text(secLabel, M, y);
  const slW = d.getTextWidth(secLabel);

  d.setFontSize(8); ink(d, C.muted);
  const cntTxt = recs.length + (recs.length === 1 ? ' item' : ' items');
  d.text(cntTxt, PAGE_W - M, y, { align: 'right' });
  const cntW = d.getTextWidth(cntTxt);

  stroke(d, C.border); d.setLineWidth(0.75);
  d.line(M + slW + 12, y - 3, PAGE_W - M - cntW - 12, y - 3);
  y += 14;

  // Cards with page-break handling
  let pageNum = 1;
  for (let i = 0; i < recs.length; i++) {
    const h = card(d, M, 0, CW, recs[i], i + 1, false);
    if (y + h > CONTENT_BOTTOM) {
      drawFooter(d, pageNum, 0);
      d.addPage(); pageBg(d); pageNum++;
      y = 54;
    }
    fill(d, C.card); stroke(d, C.border); d.setLineWidth(0.9);
    d.roundedRect(M, y, CW, h, 12, 12, 'FD');
    card(d, M, y, CW, recs[i], i + 1, true);
    y += h + 10;
  }

  // Disclaimer
  y += 2;
  const disclaimerText = protocol.disclaimer ||
    'Generated by NatureScripts for educational purposes only. Not a medical diagnosis and not a substitute for advice from a licensed provider. Consult your healthcare provider before starting any supplement.';
  const dh = disclaimer(d, M, 0, CW, disclaimerText, false);
  if (y + dh > CONTENT_BOTTOM) {
    d.addPage(); pageBg(d); pageNum++;
    y = 54;
  }
  disclaimer(d, M, y, CW, disclaimerText, true);

  // Footers on every page
  const total = d.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    d.setPage(p);
    drawFooter(d, p, total);
  }

  return d.output('blob');
}
