/**
 * 50 rotating health concern suggestions for the dashboard.
 * Displayed 3 at a time, cycling every few seconds.
 */
export const HEALTH_SUGGESTIONS: string[] = [
  "I've been feeling really tired lately",
  "Help with falling asleep at night",
  "Digestive discomfort after meals",
  "Feeling stressed and anxious",
  "Frequent headaches throughout the week",
  "My joints are stiff in the morning",
  "I keep getting colds and infections",
  "Low energy in the afternoon",
  "Skin breakouts and irritation",
  "Trouble concentrating at work",
  "Feeling bloated after eating",
  "Seasonal allergies are bad this year",
  "Muscle soreness that won't go away",
  "I want to support my liver health",
  "Mood swings and irritability",
  "My hair is thinning",
  "Trouble staying asleep at night",
  "I feel burned out and overwhelmed",
  "Support during cold and flu season",
  "Acid reflux and heartburn",
  "Waking up feeling unrested",
  "PMS symptoms every month",
  "Looking for natural allergy relief",
  "I want to improve my gut health",
  "Back pain that's been lingering",
  "Need help managing blood sugar",
  "Eye strain from screen time",
  "Feeling foggy-headed and unfocused",
  "Support for healthy blood pressure",
  "I want to boost my immune system",
  "Dry, itchy skin in winter",
  "Nausea in the mornings",
  "Knee pain when walking",
  "Looking for natural pain relief",
  "I want more energy for workouts",
  "Help with sugar cravings",
  "Night sweats and hot flashes",
  "Constipation and irregularity",
  "I bruise easily",
  "Sinus congestion that won't clear",
  "Feeling restless and on edge",
  "My nails are brittle and breaking",
  "Support for healthy cholesterol",
  "Recovering from a long illness",
  "Tension in my neck and shoulders",
  "Hormonal imbalance support",
  "Water retention and puffiness",
  "I want to support bone health",
  "Occasional dizziness or lightheadedness",
  "Looking for a general wellness protocol",
];
